# Generated by Django 5.2.12 on 2026-04-01 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Chờ xử lý'), ('paid', 'Đã thanh toán'), ('shipping', 'Đang giao'), ('completed', 'Hoàn tất'), ('cancel', 'Đã hủy')], default='pending', max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('payment_method', models.CharField(choices=[('COD', 'Thanh toán khi nhận hàng'), ('QR', 'Chuyển khoản QR Banking')], default='COD', max_length=10)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr/')),
                ('transfer_code', models.CharField(blank=True, max_length=64)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
    ]
